{% set name = "lipyphilic" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lipyphilic-{{ version }}.tar.gz
  sha256: db58466f4a78962cd274f19c08dc7413f360ca22ce86f3bea908716a3943657d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.10
    - maturin <2.0
  run:
    - attrs
    - numpy
    - scipy
    - pandas
    - matplotlib
    - freud
    - tidynamics
    - seaborn
    - tqdm


test:
  imports:
    - lipyphilic
    - lipyphilic.analysis
    - lipyphilic.leaflets
    - lipyphilic.transformations
    - lipyphilic.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p-j-smith/lipyphilic
  summary: A Python toolkit for analysing MD simulations of lipid membranes
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-j-smith
