{% set name = "lipyphilic" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lipyphilic-{{ version }}.tar.gz
  sha256: fdcc39e2806da602f25b7bae5841ee0b6966e0196c09b706ff1f66ac866313b2

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cd rust
    - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml
  skip: true  # [ py<311]

requirements:
  build:
    - python >=3.11,<3.14                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin <2.0
    - cargo-bundle-licenses
  host:
    - python
    - numpy  >=2.0
    - maturin <2.0
    - pip
  run:
    - python
    - attrs
    - numpy >=2.0
    - scipy
    - pandas
    - matplotlib-base
    - mdanalysis
    - freud
    - tidynamics
    - seaborn
    - tqdm

test:
  imports:
    - lipyphilic
    - lipyphilic.analysis
    - lipyphilic.leaflets
    - lipyphilic.transformations
    - lipyphilic.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p-j-smith/lipyphilic
  summary: A Python toolkit for analysing MD simulations of lipid membranes
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - RubenChM
    - p-j-smith
