{% set name = "lipyphilic" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lipyphilic-{{ version }}.tar.gz
  sha256: cd00b2caa3553e5bb1e206f0852308bfbb9c6f2753f13b8c51b6075db9ddfba6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - freud >=2.4.1
    - mdanalysis >=2.0
    - tidynamics
    - numpy >=1.16
    - pandas >=1.1
    - python >=3.6
    - scipy
    - tqdm
    - mock # required by MDAnalysis
    - cython # required by gsd and Freud
    - matplotlib
    - seaborn

test:
  imports:
    - lipyphilic
    - lipyphilic.lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p-j-smith/lipyphilic
  summary: A Python toolkit for analysing MD simulations of lipid membranes
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-j-smith
