{% set name = "lipyphilic" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lipyphilic-{{ version }}.tar.gz
  sha256: db58466f4a78962cd274f19c08dc7413f360ca22ce86f3bea908716a3943657d

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cd rust
    - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml
  skip: true  # [ py==39 ]

requirements:
  build:
    - python >=3.10,<3.13                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin <2.0
    - cargo-bundle-licenses
  host:
    - python {{ python }}
    - maturin <2.0
    - pip
  run:
    - python
    - attrs
    - numpy <2.0
    - scipy
    - pandas
    - matplotlib-base
    - mdanalysis
    - freud
    - tidynamics
    - seaborn
    - tqdm

test:
  imports:
    - lipyphilic
    - lipyphilic.analysis
    - lipyphilic.leaflets
    - lipyphilic.transformations
    - lipyphilic.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p-j-smith/lipyphilic
  summary: A Python toolkit for analysing MD simulations of lipid membranes
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - RubenChM
    - p-j-smith
